### ISSUE TITLE
双拼方案下，怎么设置自定义短语之类的啊？

### ISSUE THREAD

**Issue by asiyoua** [kchen0x/rime-crane#1]
我看描述里写
#自定义文本
#适用于全拼，在方案的 custom_phrase/user_dict 指定；
#双拼默认为 custom_phrase_double.txt 需要手动创建。

但是……创建了double以后，里面应该是什么内容？

**Comment by asiyoua** [comment]
双拼模式下，输入rq都没有对应日期出现，emoji显示也不太全面。
比如我想打出😊，如果我输入wx，出现的只有🤔

**Comment by kchen0x** [comment]
您的问题是【雾凇】的部分，请到 https://github.com/iDvel/rime-ice 下去咨询
