### ISSUE TITLE
雾凇词库的问题

### ISSUE THREAD

**Issue by queyuewutong** [kchen0x/rime-crane#11]
请问一下作者，这个雾凇词库是八个月之前的吗？我看是八个月之前更新的

**Comment by kchen0x** [comment]
是的。词库不定期更新。
我明天可以更新一下。

**Comment by kchen0x** [comment]
刚刚看了看雾凇的词库，最近有多次 Breaking Change，更新需要代码重合并。我会等雾凇多稳定迭代一段时间再进行整体合并。

短期不会进行词库更新。

**Comment by queyuewutong** [comment]
> 刚刚看了看雾凇的词库，最近有多次 Breaking Change，更新需要代码重合并。我会等雾凇多稳定迭代一段时间再进行整体合并。
> 
> 短期不会进行词库更新。

收到，谢谢！

**Comment by kchen0x** [comment]
已经更新到最新的词库。
