### ISSUE TITLE
win下使用皮肤在哪个文件

### ISSUE THREAD

**Issue by chca2** [kchen0x/rime-crane#14]
首先感谢作者，好活儿！
使用weasel.custom.yaml定义的皮肤只显示在小鹤双拼（雾凇）上，所以想知道小鹤音形的皮肤是使用的哪个文件？

**Comment by chca2** [comment]
好像是在xhup.schema.yaml文件，这个可以用custom文件来patch吗？

**Comment by chca2** [comment]
好像还是不行

**Comment by kchen0x** [comment]
晚些时候我测试一下。其实小狼毫的皮肤功能做得并不太好，我都没有刻意调整。

**Comment by chca2** [comment]
OK

**Comment by snhun** [comment]
> 首先感谢作者，好活儿！ 使用weasel.custom.yaml定义的皮肤只显示在小鹤双拼（雾凇）上，所以想知道小鹤音形的皮肤是使用的哪个文件？

同问题，皮肤设置只在双拼上生效，音形上没反应

**Comment by snhun** [comment]
xhup.schema.yaml
好像是设置里固定了皮肤，但没找到这两个皮肤文件
删掉就正常了
`style:
  color_scheme: crane
  color_scheme_dark: crane
  horizontal: true

preset_color_schemes:
  # 凇鹤版小鹤双拼输入法皮肤
  crane:
    name: "雪下鹤"
    author: "水猫 <kchen0x@gmail.com>"
    back_color: 0xE3E3E3                    # 候选条背景色
    border_color_width: 2
    border_color: 0x545554                  # 边框色
    border_height: 4                        # 窗口边界高度，大于圆角半径才生效
    border_width: 4                         # 窗口边界宽度，大于圆角半径才生效
    candidate_format: "\u2005%@\u2005"      # 取消掉候选序号，用 1/6 em 空格 U+2005 包围候选词，这样更边距更舒服
    corner_radius: 4                        # 窗口圆角半径
    hilited_text_color: 0x000000            # 编码高亮
    hilited_back_color: 0xffffff            # 编码背景高亮
    hilited_candidate_label_color: 0xeeeeee # 首选编号色
    hilited_candidate_text_color: 0xffffff  # 首选文字色
    hilited_candidate_back_color: 0x545554  # 首选背景色
    hilited_comment_text_color: 0xcccccc    # 首选提示字母色
    label_color: 0x555555                             # 次选编号色
    candidate_text_color: 0x000000                    # 次选文字色
    candidate_back_color: 0xffffff                    # 次选背景色
    comment_text_color: 0x555555                      # 次选提示字母色
    # horizontal: true                        # 候选窗横向显示
    font_point: 16                          # 候选窗文字字号
    label_font_point: 12                    # 候选窗编号字号
    # inline_preedit: true                    # 开启嵌入编码
    # inline_candidate: true                  # 开启嵌入候选
    text_color: 0x333333                    # 编码行文字颜色，24位色值，16进制，BGR顺序

  # 原版小鹤双拼输入法皮肤
  metro:
    author: "flypy.com"
    back_color: 0xffffff                    # 候选条背景色
    border_color_width: 1
    border_color: 0xe89f00                  # 边框色
    border_height: 8                        # 窗口边界高度，大于圆角半径才生效
    border_width: 8                         # 窗口边界宽度，大于圆角半径才生效
    candidate_format: "%c\u2005%@"          # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
    corner_radius: 6                        # 窗口圆角半径
    #hilited_corner_radius: 6                # 高亮圆角
    hilited_text_color: 0x000000            # 编码高亮
    hilited_back_color: 0xffffff            # 编码背景高亮
    hilited_candidate_label_color: 0xeeeeee # 首选编号色
    hilited_candidate_text_color: 0xffffff  # 首选文字色
    hilited_candidate_back_color: 0xe89f00  # 首选背景色
    hilited_comment_text_color: 0xcccccc    # 首选提示字母色
    label_color: 0x555555                             # 次选编号色
    candidate_text_color: 0x000000                    # 次选文字色
    candidate_back_color: 0xffffff                    # 次选背景色
    comment_text_color: 0x555555                      # 次选提示字母色
    horizontal: true                        # 候选窗横向显示
    font_point: 18                          # 候选窗文字字号
    label_font_point: 14                    # 候选窗编号字号
    inline_preedit: true                    # 开启嵌入编码
    name: "metro"
    text_color: 0x333333                    # 编码行文字颜色，24位色值，16进制，BGR顺序`

**Comment by chca2** [comment]
> xhup.schema.yaml 好像是设置里固定了皮肤，但没找到这两个皮肤文件 删掉就正常了
> 
> ```
> style:
>   color_scheme: crane
>   color_scheme_dark: crane
>   horizontal: true
> 
> preset_color_schemes:
>   # 凇鹤版小鹤双拼输入法皮肤
>   crane:
>     name: "雪下鹤"
>     author: "水猫 <kchen0x@gmail.com>"
>     back_color: 0xE3E3E3                    # 候选条背景色
>     border_color_width: 2
>     border_color: 0x545554                  # 边框色
>     border_height: 4                        # 窗口边界高度，大于圆角半径才生效
>     border_width: 4                         # 窗口边界宽度，大于圆角半径才生效
>     candidate_format: "\u2005%@\u2005"      # 取消掉候选序号，用 1/6 em 空格 U+2005 包围候选词，这样更边距更舒服
>     corner_radius: 4                        # 窗口圆角半径
>     hilited_text_color: 0x000000            # 编码高亮
>     hilited_back_color: 0xffffff            # 编码背景高亮
>     hilited_candidate_label_color: 0xeeeeee # 首选编号色
>     hilited_candidate_text_color: 0xffffff  # 首选文字色
>     hilited_candidate_back_color: 0x545554  # 首选背景色
>     hilited_comment_text_color: 0xcccccc    # 首选提示字母色
>     label_color: 0x555555                             # 次选编号色
>     candidate_text_color: 0x000000                    # 次选文字色
>     candidate_back_color: 0xffffff                    # 次选背景色
>     comment_text_color: 0x555555                      # 次选提示字母色
>     # horizontal: true                        # 候选窗横向显示
>     font_point: 16                          # 候选窗文字字号
>     label_font_point: 12                    # 候选窗编号字号
>     # inline_preedit: true                    # 开启嵌入编码
>     # inline_candidate: true                  # 开启嵌入候选
>     text_color: 0x333333                    # 编码行文字颜色，24位色值，16进制，BGR顺序
> 
>   # 原版小鹤双拼输入法皮肤
>   metro:
>     author: "flypy.com"
>     back_color: 0xffffff                    # 候选条背景色
>     border_color_width: 1
>     border_color: 0xe89f00                  # 边框色
>     border_height: 8                        # 窗口边界高度，大于圆角半径才生效
>     border_width: 8                         # 窗口边界宽度，大于圆角半径才生效
>     candidate_format: "%c\u2005%@"          # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
>     corner_radius: 6                        # 窗口圆角半径
>     #hilited_corner_radius: 6                # 高亮圆角
>     hilited_text_color: 0x000000            # 编码高亮
>     hilited_back_color: 0xffffff            # 编码背景高亮
>     hilited_candidate_label_color: 0xeeeeee # 首选编号色
>     hilited_candidate_text_color: 0xffffff  # 首选文字色
>     hilited_candidate_back_color: 0xe89f00  # 首选背景色
>     hilited_comment_text_color: 0xcccccc    # 首选提示字母色
>     label_color: 0x555555                             # 次选编号色
>     candidate_text_color: 0x000000                    # 次选文字色
>     candidate_back_color: 0xffffff                    # 次选背景色
>     comment_text_color: 0x555555                      # 次选提示字母色
>     horizontal: true                        # 候选窗横向显示
>     font_point: 18                          # 候选窗文字字号
>     label_font_point: 14                    # 候选窗编号字号
>     inline_preedit: true                    # 开启嵌入编码
>     name: "metro"
>     text_color: 0x333333                    # 编码行文字颜色，24位色值，16进制，BGR顺序
> ```

或者在xhup.schema.yaml中直接定义皮肤也可以，跟Crane和Metro格式相同即可。

**Comment by kchen0x** [comment]
是的 小鹤音形 的皮肤设置是单独在 xhup.schema.yaml 中定义的。
