### ISSUE TITLE
仓输入法的“部署时覆盖词库文件”是否应打开

### ISSUE THREAD

**Issue by chca2** [kchen0x/rime-crane#15]
“部署时覆盖词库文件”选项的说明是“如果您未使用自造词功能，请保持开启状态”。
考虑到淞鹤是结合了音形和双拼（拼音），使用前者时候应开启、后者不应开启。
实践中，关闭时也会发生xhup_dicts中的词语定义后无法生效的情况。但是如果开启该功能，是不是又会影响使用双拼（拼音）时候的自造词功能（userdb）?

**Comment by kchen0x** [comment]
好问题，理论上确实应该是应该是有冲突的。

这个问题估计需要 @imfuxiao 来解决一下。比较好的做法是，*关闭*“部署时覆盖词库文件”选项的时候只影响用户词库 userdb 而不影响码表文件 xhup_dicts/* 才对，这里的逻辑也要请作者核实一下。

可以给仓提个 issue 问问。https://github.com/imfuxiao/Hamster/issues

**Comment by chca2** [comment]
好的，我提一下
