### ISSUE TITLE
缺少凇鹤方案的“凇”字编码

### ISSUE THREAD

**Issue by kimberlytor** [kchen0x/rime-crane#16]
提一个小问题，目前的词库中要打出凇鹤词库中的“凇”字的话需要使用万能码才能打出，即ssd`，目前我是将编码加入了xhup.user.top.dict.yaml中，作为这个方案的名字，希望这个字加入主词库

**Comment by kchen0x** [comment]
这个是“小鹤音形”原作者“鹤大”没有把这个字加入到主词库里面去，所以我也是添加到用户编码中去使用的。
