### ISSUE TITLE
ios上仓输入法配置

### ISSUE THREAD

**Issue by ZhXWei** [kchen0x/rime-crane#19]
ios上仓输入法怎么配置使用，小鹤音形的部署方案么？

**Comment by kchen0x** [comment]
整个文件夹上传到“仓输入法”（或者通过 icloud 文件同步也可以），然后点击部署。输入方案中勾选“小鹤音形”就可以了。

**Comment by kchen0x** [comment]
完整方法和原来导入雾凇的方法是一样的：

https://github.com/imfuxiao/Hamster/wiki/%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%22%E9%9B%BE%E6%B7%9E%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88%22
