### ISSUE TITLE
小鹤双拼开启辅助码

### ISSUE THREAD

**Issue by CarameowCookie** [kchen0x/rime-crane#2]
请问能否通过修改小鹤双拼的配置文件，来为小鹤双拼开启鹤形辅助码？

**Comment by kchen0x** [comment]
小鹤的码表是不公开的，现网所有的方案都是通过反查挂载码表的方式清洗出辅码，很难保证准确性，或者需要进行大量的工作。所以我并不打算在本项目中启用辅码功能。但是如果你很喜欢小鹤的双拼+形码做为辅助码的方案，可以看看这个项目： https://gitee.com/functoreality/rime-flypy-zrmfast

**Comment by nanoarchaeota** [comment]
建议可以参照这个项目[https://github.com/HowcanoeWang/rime-lua-aux-code](https://github.com/HowcanoeWang/rime-lua-aux-code)试一下通过`;`键引导查找辅助码，这样就不用做辅助码的词库了。

**Comment by kchen0x** [comment]
看了几个方案实施的效果其实都不太好。你给的这个方案里面，作者的Lua脚本总是会出现 `;` 键没有被移除的问题。

> 建议可以参照这个项目https://github.com/HowcanoeWang/rime-lua-aux-code试一下通过`;`键引导查找辅助码，这样就不用做辅助码的词库了。我有辅助码文件，有需要可回复我。

**Comment by nanoarchaeota** [comment]
> Ref

是的，下午我也试了下，确实存在这样的问题。下午又看了个魔改自然码的，也是在词库中去加辅助码，这样做词库的工作量很大。

**Comment by kchen0x** [comment]
另一方面，我确实也觉得使用辅码的方式有点背离双拼→音形码的设计初衷。

**Comment by gaboolic** [comment]
> 看了几个方案实施的效果其实都不太好。你给的这个方案里面，作者的Lua脚本总是会出现 `;` 键没有被移除的问题。
> 
> > 建议可以参照这个项目[https://github.com/HowcanoeWang/rime-lua-aux-code试一下通过`;`键引导查找辅助码，这样就不用做辅助码的词库了。我有辅助码文件，有需要可回复我。](https://github.com/HowcanoeWang/rime-lua-aux-code%E8%AF%95%E4%B8%80%E4%B8%8B%E9%80%9A%E8%BF%87%60;%60%E9%94%AE%E5%BC%95%E5%AF%BC%E6%9F%A5%E6%89%BE%E8%BE%85%E5%8A%A9%E7%A0%81%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%B1%E4%B8%8D%E7%94%A8%E5%81%9A%E8%BE%85%E5%8A%A9%E7%A0%81%E7%9A%84%E8%AF%8D%E5%BA%93%E4%BA%86%E3%80%82%E6%88%91%E6%9C%89%E8%BE%85%E5%8A%A9%E7%A0%81%E6%96%87%E4%BB%B6%EF%BC%8C%E6%9C%89%E9%9C%80%E8%A6%81%E5%8F%AF%E5%9B%9E%E5%A4%8D%E6%88%91%E3%80%82)

我基于这个项目和雾凇词库做了 https://github.com/gaboolic/rime-shuangpin-fuzhuma
