### ISSUE TITLE
求教一下如何关闭自动造句功能（或者是联想？）

### ISSUE THREAD

**Issue by LiangSam** [kchen0x/rime-crane#20]
很感谢大佬开发的这款输入法，让我再Rime上也能用到这么丝滑的小鹤双拼，这比之前的【小鶴雙拼】要流畅许多。

我在使用中有一个问题，就是如何关闭它的自动联想功能。例如我在输入“一如既往”时，后面会自动联想出“一如既往地关心”等句子，我尚且不知道这是什么功能，也不知道该如何关闭它。

![微信图片_20240704102437](https://github.com/kchen0x/rime-crane/assets/38411915/a45bce23-72eb-45ec-b0cf-ebb890c3ed1c)
![微信图片_20240704102431](https://github.com/kchen0x/rime-crane/assets/38411915/113ec26b-0ad8-4521-8a05-ba9e34644d96)

希望大佬能给点建议，主要是觉得这有点影响打字体验，不够简洁。

**Comment by kchen0x** [comment]
先说一下，你红框中的词汇主要来自于雾凇输入法里面的【扩展词库】和【腾讯词向量库】。当输入四个字以上时就会开始匹配词库内容。
其实影响不大，但是如果你真的不喜欢，就可以在 rime_ice.dict.yaml 文件中注释掉不想用的词库文件

```
import_tables:
  - cn_dicts/8105     # 字表
  # - cn_dicts/41448  # 大字表（按需启用）
  - cn_dicts/base     # 基础词库
  - cn_dicts/ext      # 扩展词库
  - cn_dicts/tencent  # 腾讯词向量（大词库，部署时间较长）
  - cn_dicts/others   # 一些杂项
```

但是这两个词库里面也有一些高质量的词汇，如果你关闭掉也就意味着用不了了。
<img width="169" alt="image" src="https://github.com/kchen0x/rime-crane/assets/9739009/86792fbf-ed9e-4a88-bcb5-c8a8ea652dc8">

所以根据你的情况来选择吧。

**Comment by kchen0x** [comment]
另，想要简洁，可以来学习一下【小鹤音形】。进入真正简洁的输入状态：

<img width="251" alt="image" src="https://github.com/kchen0x/rime-crane/assets/9739009/02496e98-25d5-4d51-ae62-ed1c5bb23f50">

<img width="149" alt="image" src="https://github.com/kchen0x/rime-crane/assets/9739009/ba402b5c-5075-4171-9400-6bea64ae9f5e">

**Comment by chca2** [comment]
> 另，想要简洁，可以来学习一下【小鹤音形】。进入真正简洁的输入状态：
> 
> <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/9739009/345734402-02496e98-25d5-4d51-ae62-ed1c5bb23f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ2MTQsIm5iZiI6MTcyMDA4NDMxNCwicGF0aCI6Ii85NzM5MDA5LzM0NTczNDQwMi0wMjQ5NmU5OC0yNWQ1LTRkNTEtYWU2Mi1lZDFjNWJiMjNmNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDkxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhlMjQyMTkwMjJhM2I4MWY1MDJiOWY0MDAyOWE0YWI5MWUxMzIxODc2NDlkYTQ3ZmIwYzQ2OWE1OWU0N2M2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IcuuKpAyGzZFN9Jc5jvogDTYU_V7itWQUGwvUwhfnrw"> <img alt="image" width="149" src="https://private-user-images.githubusercontent.com/9739009/345734596-ba402b5c-5075-4171-9400-6bea64ae9f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ2MTQsIm5iZiI6MTcyMDA4NDMxNCwicGF0aCI6Ii85NzM5MDA5LzM0NTczNDU5Ni1iYTQwMmI1Yy01MDc1LTQxNzEtOTQwMC02YmVhNjRhZTlmNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDkxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJkMWNiN2UxYjg0MmVkZjIwYTQ5MDUzZDE5OWUyOGM4ZWI2MDgxYjU5NDI4NmMzYWEzY2QzYmY5NmYxMWVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qAPjQbOTdv-pg_eEp7T7tu3cmAQbRl9Q3pI-o6NTYTM">

大佬，你用音形打单吗？自己造词吗？感觉用惯拼音提笔忘字，使用音形还是有点麻烦的，造词又会违背音形的初衷。

**Comment by kchen0x** [comment]
> > 另，想要简洁，可以来学习一下【小鹤音形】。进入真正简洁的输入状态：
> > <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/9739009/345734402-02496e98-25d5-4d51-ae62-ed1c5bb23f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ2MTQsIm5iZiI6MTcyMDA4NDMxNCwicGF0aCI6Ii85NzM5MDA5LzM0NTczNDQwMi0wMjQ5NmU5OC0yNWQ1LTRkNTEtYWU2Mi1lZDFjNWJiMjNmNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDkxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhlMjQyMTkwMjJhM2I4MWY1MDJiOWY0MDAyOWE0YWI5MWUxMzIxODc2NDlkYTQ3ZmIwYzQ2OWE1OWU0N2M2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IcuuKpAyGzZFN9Jc5jvogDTYU_V7itWQUGwvUwhfnrw"> <img alt="image" width="149" src="https://private-user-images.githubusercontent.com/9739009/345734596-ba402b5c-5075-4171-9400-6bea64ae9f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ2MTQsIm5iZiI6MTcyMDA4NDMxNCwicGF0aCI6Ii85NzM5MDA5LzM0NTczNDU5Ni1iYTQwMmI1Yy01MDc1LTQxNzEtOTQwMC02YmVhNjRhZTlmNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDkxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJkMWNiN2UxYjg0MmVkZjIwYTQ5MDUzZDE5OWUyOGM4ZWI2MDgxYjU5NDI4NmMzYWEzY2QzYmY5NmYxMWVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qAPjQbOTdv-pg_eEp7T7tu3cmAQbRl9Q3pI-o6NTYTM">
> 
> 大佬，你用音形打单吗？自己造词吗？感觉用惯拼音提笔忘字，使用音形还是有点麻烦的，造词又会违背音形的初衷。

有简打简，有词打词，无词打单。
常用的词汇就那么多，熟悉熟悉就好了。

提笔忘字的时候实在不行有万能码，或者打个词语去选也行。
