### ISSUE TITLE
小鹤音形的自定义词库是否支持调频？

### ISSUE THREAD

**Issue by chca2** [kchen0x/rime-crane#26]
小鹤音形的macOS官方挂接方案，top和User词库支持的编码格式为“字词+Tab符+编码”，在本方案中，音形的词库是否也支持？

**Comment by kchen0x** [comment]
可以：
- `xhup_dicts/xhup.user.dict.yaml`
- `xhup_dicts/xhup.user.top.dict.yaml`

这两个文件分别是用户词和置顶词。

**Comment by chca2** [comment]
> 可以：
> 
> - `xhup_dicts/xhup.user.dict.yaml`
> 
> - `xhup_dicts/xhup.user.top.dict.yaml`
> 
> 
> 
> 这两个文件分别是用户词和置顶词。

Sorry, I meant字词-编码-权重这种格式，来决定自造词在什么位置。

**Comment by kchen0x** [comment]
支持的，默认权重是1，你输入数值之后就可以按大到小重码排序，不过我觉得还是按码表顺序直观一点，一眼就能看出来。权重适合自造词库比较大的时候。
