### ISSUE TITLE
虎码和小鹤音形的使用体验

### ISSUE THREAD

**Issue by KeithW0726** [kchen0x/rime-crane#27]
用小鹤音形有段时间，对小鹤音形的弊端也渐渐感受到了，开始萌生了想转虎码的念头，不知道两者都接触的楼主感受如何？

**Comment by kchen0x** [comment]
我刚刚才开始使用虎码，没有发言权。
因为练习不给力500击键还没有过6，所以现在我主力还在使用小鹤音形。
