### ISSUE TITLE
小鹤音形的词库好像比官网的少了一点

### ISSUE THREAD

**Issue by RainGoal** [kchen0x/rime-crane#31]
想请教下，这个词库是不是和小鹤音形官网的词库比有点缺漏，比如官网的可以使用kkuz打出“快手”，但是这个词库是无法直接打出这个词的

**Comment by kchen0x** [comment]
确实如此，因为小鹤音形官网的词库是闭源的，我其实拿不到真实、完整的首选词。
该项目的首选词来自于官网鹤大的百度输入法挂接词库。属于官方，但是不保证能和Windows词库完全一致。

**Comment by RainGoal** [comment]
嗯嗯，明白了，感谢提供的开源码表词库🙏
