### ISSUE TITLE
关于顶功上屏模式的问题

### ISSUE THREAD

**Issue by kimberlytor** [kchen0x/rime-crane#5]
请问下如果采用顶功上屏方式的话，只要碰到词的第一个字的第一个形码不存在的话，就会忽略后面可能存在的词，举例如“主体、设置”，因为“vhv uev”无对应单字，到第三个键时就会自动清屏，这样这些词只能打单打出来，请问如何修改设置能够优化这个问题呢？

**Comment by kimberlytor** [comment]
找到设置了，把auto_clear改成max_length就行了

**Comment by kimberlytor** [comment]
不过还有一点比较奇怪的，像短语这个词，dry也是没有对应码的词，但是auto模式下这个会提示“短语”这个词而不是清屏，我看了下flypy.dict.yaml文件里这些词都在

**Comment by kchen0x** [comment]
fixed
