### ISSUE TITLE
关于辅助码的问题

### ISSUE THREAD

**Issue by fgvigu** [kchen0x/rime-crane#6]
大佬，请问rime的小鹤双拼模式下怎么加辅助码呢，我试过在词库里加单字音形码，但是打字的时候好像没有生效

**Comment by gaboolic** [comment]
可以试试https://github.com/gaboolic/rime-shuangpin-fuzhuma

**Comment by kchen0x** [comment]
> 可以试试https://github.com/gaboolic/rime-shuangpin-fuzhuma

nice！
