### ISSUE TITLE
无法在仓输入法中使用

### ISSUE THREAD

**Issue by suibianzai** [kchen0x/rime-crane#9]
你好！最近发现ios上有个rime输入法，我按照它的说明导入凇鹤拼音的方案[https://github.com/imfuxiao/Hamster/wiki/%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%22%E9%9B%BE%E6%B7%9E%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88%22](url)，去掉了others和read me，其他全部导入清空后的rime文件夹，但是点重新部署之后，app提示未能读取数据，因为它的格式不正确（见下图），请问是我哪里操作错误吗？
设备是iphone13，ios15
![IMG_16D7AB92376B-1](https://github.com/kchen0x/rime-crane/assets/42022663/6b19653b-3aff-4b10-a70f-569a9031a3e0)

**Comment by kchen0x** [comment]
好的，后续我会根据“仓输入法”的文档更新 hamster 配置。
